apiVersion: v1
kind: ConfigMap
metadata:
  name: gridops-config
  namespace: gridops-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DATABASE_URL: "jdbc:postgresql://postgres-cluster.gridops-prod.svc.cluster.local:5432/gridops_db"
  REDIS_HOST: "redis-master.gridops-prod.svc.cluster.local"
  REDIS_PORT: "6379"
  ANALYTICS_SERVICE_URL: "http://gridops-analytics.gridops-prod.svc.cluster.local:8000"
  LOG_LEVEL: "INFO"
